### ISSUE TITLE
Support for Playing User Modules/Files

### ISSUE THREAD

**Issue by lunar-sh** [DrSnuggles/AYSir#1]
Hi @DrSnuggles. I think your player is great. The only issue is that currently people can't play their own modules.
Are you ever thinking of adding that functionality?

Regards,
Dylan

**Comment by DrSnuggles** [comment]
Thats already included, but not yet documented...
Just drag n drop a file in and it should play.

Have fun!
Max

**Comment by lunar-sh** [comment]
Ah thanks!
